### PR TITLE
Added 4 important Add-ons.

### PR DESCRIPTION
**Pull request by VatsalJagani**

### CODE REVIEW

**Review by mahirchavda — CHANGES_REQUESTED** [review]
For the powershell inputs, we need to put absolute path with original Windows app.

**Comment by VatsalJagani** [comment]
> For the powershell inputs, we need to put absolute path with original Windows app.

Thanks Mahir, nice catch. Fixed it now.

**Review by mahirchavda — APPROVED** [review]
Do we want source=powershell? i think by default, it will be script name.

**Comment by VatsalJagani** [comment]
> Do we want source=powershell? i think by default, it will be script name.

I don't think so. Its true if it is modular input powershell.

**Pull request merged**
